### ISSUE TITLE
Is there updated wiki?

### ISSUE THREAD

**Issue by kandeshvari** [embox/embox#1265]
I have found old one at http://web.archive.org/web/20160105031702/https://code.google.com/p/embox/wiki/QuickOverview?wl=ru

I there a newer version? Could someone export/import at least old wiki to github?

It's connected with my offtop but main question - what is the status of embox development? Is it stalled, abandoned or sluggishly developing? Is there future for embox?

**Comment by anton-bondarev** [comment]
@kandeshvari 
Hi, we created a separate github repo for Embox documentations ([https://github.com/embox/embox-docs](https://github.com/embox/embox-docs) ). So it's better to use it for documentations issues.
