### ISSUE TITLE
usermode86/debug doesn't restore terminal settings

### ISSUE THREAD

**Issue by AntonKozlov** [embox/embox#1537]
After (forceful) exit from usermode86/debug, terminal settings are not restored
```
$ make confload-usermode86/debug
$ make
$ ./build/base/bin/embox
...
CTRL+C
```

**Comment by Ahish9009** [comment]
Hi, I would like to work on this issue.
I have built the embox shell, could you point to me a good place to get started to resolve this issue?

**Comment by bartekxk** [comment]
Hello,
What settings are not properly restored? I'm trying to reproduce the error but everything looks fine.

Thanks.

**Comment by AntonKozlov** [comment]
I filed the bug after conversation with @anton-bondarev. 

AFAIR, after embox forcefully terminated (i.e. ctrl-c or with `kill` from another terminal on linux), terminal doesn't do echo of typed symbols, enter key doesn't introduce new line (or makes '\n' without '\r', don't remember now)

**Comment by worldinmyfist** [comment]
Hi, Can I work on this issue ?

**Comment by Ahish9009** [comment]
Hi
I am also unable to reproduce the error. I tried echo'ing various symbols, and using the enter key. Everything seems to be working fine for me.

**Comment by AntonKozlov** [comment]
Please check screencast with the issue demonstrated.
Is behavior on your machine different?

https://asciinema.org/a/304411

I hit ctrl-c during boot process. Then I hit enter few times -- shell invitations expected on separate lines, but they are on the same. 
Then I tried typing `1<enter>2<enter>...`. I expected to see number as I type them, but they are not displayed -- I see only shell error after the input processed. 
Typing `reset` blindly resets the terminal. 
Just for reference, correct behavior for same keys pressed https://asciinema.org/a/304416

**Comment by Ahish9009** [comment]
![output](https://user-images.githubusercontent.com/26454938/75192275-eb62c700-5779-11ea-9df9-f4427e8a7660.gif)

It seems to be working fine on my machine.

**Comment by AntonKozlov** [comment]
I see, interesting. I use xterm on linux, it probably matters. It may be my
environment as well.
I would suggest not to spend too much efforts on reproducing, it's warmup
issue and it's not very disturbing. Thanks for checking! I think it made a
contribution to understanding of the problem the problem.

**Comment by anton-bondarev** [comment]
@Ahish9009 @bartekxk @AntonKozlov Thanks
Now I also can't reproduce the problem!
