### ISSUE TITLE
npf porting

### ISSUE THREAD

**Issue by Deryugin** [embox/embox#1643]
We got request for porting this lib: https://github.com/rmind/npf

I did a little research on dependencies, some of them are ported in [npf_porting](https://github.com/embox/embox/tree/npf_porting) branch.

It turned out that we need following improvements:
* bsd/queue support #1644 
* Extend pthread compatibility #1645 
* Using different compilers for `libtool` in `third_party`

**Comment by sobhaniiest** [comment]
Hi, I would like to work on this.
