### ISSUE TITLE
bsd/queue support

### ISSUE THREAD

**Issue by Deryugin** [embox/embox#1644]
Right now we don't have any modules for bsd compatibility, I suggest creating a separate directory for it, like `src/compat/bsd/`.

We need to implement macros/functions from BSD `queue.h`, it can be tested with #1643

**Comment by AntonKozlov** [comment]
Can we just take them as is
https://github.com/freebsd/freebsd/blob/master/sys/sys/queue.h ? It's BSD
too

src/compat/bsd is nice place, but on my Linux system it's just in
/usr/include
```
$ head /usr/include/sys/queue.h
/*
 * Copyright (c) 1991, 1993
 *      The Regents of the University of California.  All rights reserved.
 *
```

**Comment by Deryugin** [comment]
Yeah, probably we can just take this file.

As for the header directory, we're trying to avoid putting header files into `src/include` by using `@IncludeExport`, otherwise `src/include` directory becomes a bit messy.

**Comment by subhojit-ghorai** [comment]
Hi! Can I work on this issue? I have been doing research on this issue.

**Comment by Deryugin** [comment]
Hi, 
Sure!
