### ISSUE TITLE
Implement strptime()

### ISSUE THREAD

**Issue by Deryugin** [embox/embox#1685]
strptime() is a POSIX function to convert time from string representation to `struct tm`. Refer to `man 3 strptime` for more details.

It's necessary to add some test and put them in some templates.

Stub for this function was added in #1631 already.

**Comment by MrSquanchee** [comment]
@Deryugin , I would like to be assigned to work on this issue and implement the `strptime()` function.

**Comment by Deryugin** [comment]
@MrSquanchee I'm sorry, one of the developers is already working on it at the moment.
P.S. Let's finish #1740 at first.

**Comment by anton-bondarev** [comment]
@Deryugin is it closed by #1790 ?

**Comment by Deryugin** [comment]
Yes, it's closed now :)
