### ISSUE TITLE
Xen block device driver

### ISSUE THREAD

**Issue by AntonKozlov** [embox/embox#1694]
Discussion on imlementation of block device for xen

**Comment by anton-bondarev** [comment]
Hi, 
I don't understand what's difference between block_dev for Xen and another block_dev?

**Comment by AntonKozlov** [comment]
Hmm, do we have xen block_dev driver already?

**Comment by anton-bondarev** [comment]
Ok, I've understood. But I think the issue description should correct. 

>  Implement a driver for one of block devices in Xen. 

for example.
It seems more clear.

**Comment by Deryugin** [comment]
> Hmm, do we have xen block_dev driver already?

I bet ramdisk will work for Xen, and it's a block device :)

**Comment by AntonKozlov** [comment]
Accidentally I started irrelevant discussion. Sorry for that.
