### ISSUE TITLE
'blockdev' command

### ISSUE THREAD

**Issue by anton-bondarev** [embox/embox#1701]
Implement of 'blockdev' command ([man 8 blockdev ](http://man7.org/linux/man-pages/man8/blockdev.8.html) )
The first implementation may include only `--getbsz` command or `--report` options. [Examples](http://fibrevillage.com/storage/291-blockdev-command-examples).

Example, getting of blockdev information may be found in 'lsblk' command

**Comment by bw-space** [comment]
I want to take up this issue, can I work on it?

**Comment by anton-bondarev** [comment]
yes, you can :)

**Comment by bw-space** [comment]
Thanks a lot, I have been going through the source code, I have seen implementations of many shell functions, but I am not able to figure out where are they called from,like:
if I type 'uname', how is it called, or where should I place my new command, so that it is found by the tish shell. Is there documentation of such related queries?

**Comment by anton-bondarev** [comment]
You can get information about how to add a new command to Embox on[ "Quick start" wiki page](https://github.com/embox/embox/wiki/Quick-Start#hello-world-application) or in embox_quick_start_en.pdf from [ documentation repo](https://github.com/embox/embox-docs/releases)

**Comment by bw-space** [comment]
Thanks, I have managed to make the first app, I am able to get the block size. What all entries should be present in the --report part?
'RO    RA   SSZ   BSZ   StartSec            Size   Device' all from here?

**Comment by anton-bondarev** [comment]
Block size and block_dev size are enough now

**Comment by bw-space** [comment]
Can you let me know, if the code in PR is alright, or needs some changes?

**Comment by anton-bondarev** [comment]
@bw-space Can you prepare PR according to the rules adopted by Embox ?

**Comment by worldinmyfist** [comment]
Can I work on this issue as well?

**Comment by Deryugin** [comment]
@worldinmyfist no. Please consider some other issue that is not assigned to anyone.
We will add more issues with "Good first issue" tag soon.

**Comment by anton-bondarev** [comment]
Closed by #2008
