### ISSUE TITLE
Time flows too fast on arm/qemu

### ISSUE THREAD

**Issue by alexkalmuk** [embox/embox#1708]
Template: `arm/qemu`
Include module `include embox.cmd.testing.ticker` in conf/mods.config and rebuild embox.

```
root@embox:/#ticker                                                             
1 sec
2 sec
3 sec
4 sec
5 sec
```

You can see time flows faster than in reality.

**Comment by layman-n-ish** [comment]
Hello, 

This looks like an interesting situation. May I work on fixing this? Thanks in advance.

**Comment by alexkalmuk** [comment]
Yes, of course.

**Comment by alexkalmuk** [comment]
@layman-n-ish Thank you! Your solution looks pretty good, so we already merged it into master.
