### ISSUE TITLE
Implement memalign for heap_simple memory allocator

### ISSUE THREAD

**Issue by alexkalmuk** [embox/embox#1713]
There are several memory allocation algorithms in Embox, one of them is heap_simple - the very basic one, which is rarely used but is useful sometimes for debugging. However, the current heap_simple implementation misses `memalign()` function, so it's required to implement it.

**Comment by bartekxk** [comment]
Hello, I would like to work on this issue.

**Comment by alexkalmuk** [comment]
Hello, great!

**Comment by bartekxk** [comment]
I created pull request. Can you review it?
 #1715 
Thanks.

**Comment by bartekxk** [comment]
You can close this task.

**Comment by alexkalmuk** [comment]
Yes, of course, thanks. btw you will use something like "Close #<issue>" or "Fix #<issue>" it will be closed automatically - https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

**Comment by alexkalmuk** [comment]
Closed by https://github.com/embox/embox/pull/1715
