### ISSUE TITLE
Extend lsusb command

### ISSUE THREAD

**Issue by alexkalmuk** [embox/embox#1714]
Add the following option to lsusb command:

(from `man lsusb`)
```
       -v, --verbose
              Tells lsusb to be verbose and display detailed information about the devices shown.
              This  includes  configuration  descriptors  for  the device's current speed.  Class
              descriptors will be shown, when available, for USB device  classes  including  hub,
              audio, HID, communications, and chipcard.
```

We already have `lsusb` in Embox, but it only prints current devices, it would be great if we can see also device descriptors at least.

This issue requires to study USB, but only very basic high-level things, without going deeper into the USB subsystem. You have to study how to get a USB descriptor and show this descriptor to user in a nice way.

**Comment by bartekxk** [comment]
Hello, I would like to work on this issue.

**Comment by alexkalmuk** [comment]
Let's finish with https://github.com/embox/embox/issues/1713 first. Then you can to choose a new one :)

**Comment by bartekxk** [comment]
Sure, I will also look at other tasks and after finishing my, I will let you know again :).

**Comment by shivamanipatil** [comment]
I woould like to work on this one.

**Comment by anton-bondarev** [comment]
@shivamanipatil You've been assigned with the issue.
Please look through our code style ( [https://github.com/embox/embox/wiki/Code-Style](https://github.com/embox/embox/wiki/Code-Style)) and git roles ( [https://github.com/embox/embox/wiki/Contributing%3A-Git-cheatsheet](https://github.com/embox/embox/wiki/Contributing%3A-Git-cheatsheet) ) to prepare PR.

**Comment by shivamanipatil** [comment]
@anton-bondarev @alexkalmuk 
![lsusb](https://user-images.githubusercontent.com/43640923/75450348-a4045280-5994-11ea-9a02-88b086d9ca81.png) 
Right now I am priting this is this fine?

**Comment by alexkalmuk** [comment]
Hi, the pattern looks good but I would recommend printing Configuration Descriptor instead of Interface Descriptor.

**Comment by alexkalmuk** [comment]
But the pattern looks nice :)

**Comment by shivamanipatil** [comment]
**struct usb_dev** contains **usb_desc_device** and **usb_desc_interface** and doesn't contain **usb_desc_configuration**. So is it fine if I add **usb_desc_configuration** to **struct usb_dev** for displaying configuration descriptors.
