### ISSUE TITLE
printf must check return value from printchar_handler

### ISSUE THREAD

**Issue by anton-bondarev** [embox/embox#1722]
printf() must return error code if printchar_handler() failed

**Comment by sk2sat** [comment]
Hi
Can I work on this issue?

**Comment by anton-bondarev** [comment]
Of course, yes!

But if you want to participate of GSoC you should also send us email and tell a bit about yourself as described on the wiki page  [https://github.com/embox/embox/wiki/Google-Summer-of-Code-2020](https://github.com/embox/embox/wiki/Google-Summer-of-Code-2020)

**Comment by sk2sat** [comment]
OK. I will send email. thanks!
