### ISSUE TITLE
arping doesn't show microseconds

### ISSUE THREAD

**Issue by alexkalmuk** [embox/embox#1723]
```
root@embox:/#arping 10.0.2.10                                                   
ARPING 10.0.2.10 from 10.0.2.16 eth0
Unicast reply from 10.0.2.10 [aa:bb:cc:dd:ee:ff]  0ms
Unicast reply from 10.0.2.10 [aa:bb:cc:dd:ee:ff]  0ms
```

Expected something like that:

```
root@embox:/#arping 10.0.2.10                                                   
ARPING 10.0.2.10 from 10.0.2.16 eth0
Unicast reply from 10.0.2.10 [aa:bb:cc:dd:ee:ff]  0.285ms
Unicast reply from 10.0.2.10 [aa:bb:cc:dd:ee:ff]  0.343ms
```

**Comment by eboswell** [comment]
In the example, are those 0.285ms microseconds or milliseconds?

**Comment by eboswell** [comment]
I would like to work on this issue

**Comment by alexkalmuk** [comment]
> In the example, are those 0.285ms microseconds or milliseconds?

0.285 milliseconds = 285 microseconds :)

**Comment by alexkalmuk** [comment]
There are possible troubles with floating-point arithmetic on CPUs with a really small amount of memory and without hardware FPU, so I would suggest you to use integer arithmetic if it is possible here. But any solution will be great, of course.

**Comment by alexkalmuk** [comment]
Fixed by https://github.com/embox/embox/pull/1741
