### ISSUE TITLE
Extending file formats for `file` command

### ISSUE THREAD

**Issue by Deryugin** [embox/embox#1730]
There is a `file` command (src/cmds/fs/file.c), currently it just checks if file is RIFF or text file.

This can be extended for ELF, PNG and GIF formats too, and it should be relatively simple.

Optionally, checking for HTML/XML/SVG file formats may be implemented too, but that's a little bit more complicated as header is not in the fixed position.

**Comment by VivekKamisetty** [comment]
Hello, I am interested in taking up this issue

**Comment by anton-bondarev** [comment]
Hello, ok. I've assigned it to you

**Comment by Deryugin** [comment]
This issue is unassigned now, so feel free to pick this task.

**Comment by El-Mohamed** [comment]
tell me more I can't understand

**Comment by checker5965** [comment]
@Deryugin @anton-bondarev Hi, I've added functionality for ELF, PNG, and GIF files. Can you assign this issue to me so that I can create a PR?

I can also try to implement HTML/XML/SVG functionality.

**Comment by alexkalmuk** [comment]
@checker5965 Hi! As far as I can see you already finished https://github.com/embox/embox/issues/1758. Let's leave this issue for other students :)

We do not require to solve more than one good first issue, but if you want you a free to choose any which is not labeled with "good first issue".

**Comment by alexkalmuk** [comment]
By the way, if you already implemented ELF and PNG, you can create PR for these two only, but let's leave other formats for students, please.

**Comment by checker5965** [comment]
@alexkalmuk Oh okay, in that case I'll just let it be and pick another issue. Hopefully someone else will take this issue up :)

**Comment by anton-bondarev** [comment]
> tell me more I can't understand

@Abnaby
[commented above](https://github.com/embox/embox/issues/1730#issuecomment-596199551)

**Comment by yog-singh** [comment]
Hello, I'm interested in solving this issue. Please assign it to me.

**Comment by anton-bondarev** [comment]
@yog-singh I've assigned it with you
