### ISSUE TITLE
math floating point tests

### ISSUE THREAD

**Issue by alexkalmuk** [embox/embox#1745]
There are no basic math tests from FP functions in Embox. Let's add something like `src/tests/math/math_test_fp.c` and test for the following functions:

```
extern double modf(double x, double *i_ptr);
extern double fmod(double x, double y);
extern int signbit(double x);
extern double fabs(double x);
extern float fabsf(float x);
extern long double fabsl(long double x);
```

(it's first several functions from src/compat/libc/math/math_builtins.h)

It's assumed the tests should be very simple, just to make sure the corresponding functions are not stubs and really doing something.

**Comment by rushilkvs** [comment]
I would like to work on this issue

**Comment by anton-bondarev** [comment]
Thanks. I've assigned it with you.
