### ISSUE TITLE
Multiple arguments for `cat` command

### ISSUE THREAD

**Issue by Deryugin** [embox/embox#1754]
Looks like `cat` command simply prints content of the last argument (i.e. ignoring all the other arguments).

What do we have now:
```
root@embox:/#cat file1 file2
<file2 content>
```

What do we need:
```
root@embox:/#cat file1 file2
<file1 content>
<file2 content>
```

This can be tested on `x86/qemu` or `arm/qemu` templates.

**Comment by sobhaniiest** [comment]
Hi, I would like to work on this.

**Comment by alexkalmuk** [comment]
Hi, ok, I assigned you.

**Comment by sobhaniiest** [comment]
Please have a look.
