### ISSUE TITLE
Multiple arguments for `ls` command

### ISSUE THREAD

**Issue by Deryugin** [embox/embox#1755]
Looks like `ls` uses only first non-option argument, so it should be fixed to accept more files as arguments.

Now it works like this:
```
root@embox:/#ls -l shadow
-rw-------       root       root        398 shadow
root@embox:/#ls -l passwd
-rw-r--r--       root       root        335 passwd
root@embox:/#ls -l shadow passwd
-rw-------       root       root        398 shadow
```

How is it expected to work:
```
root@embox:/#ls -l shadow passwd
-rw-------       root       root        398 shadow
-rw-r--r--       root       root        335 passwd
```

This can be tested on `x86/qemu` or `arm/qemu` templates.

**Comment by pdzhu** [comment]
I have solved it，but I don't think my code is very elegant. Later, I'll PR.

**Comment by anton-bondarev** [comment]
> I have solved it，but I don't think my code is very elegant. Later, I'll PR.
Ok
