### ISSUE TITLE
Implementing sp804 driver

### ISSUE THREAD

**Issue by Deryugin** [embox/embox#1769]
sp804 is a timer module which is used in various ARM boards.
Technical reference manual can be found [here](http://infocenter.arm.com/help/topic/com.arm.doc.ddi0271d/DDI0271.pdf).

It's emulated for qemu vexpress machine, which is already supported (`arm/vexpress-a9` template), so it's required to implement a driver for this timer.

```
(qemu) info mtree
    ...
    0000000010011000-0000000010011fff (prio 0, i/o): sp804
    0000000010012000-0000000010012fff (prio 0, i/o): sp804
```

**Comment by layman-n-ish** [comment]
Hello! I see that LKDDb (Linux Kernel Driver DataBase) has [support for SP804](https://cateee.net/lkddb/web-lkddb/ARM_TIMER_SP804.html). May I take that as a reference and give an attempt at the implementation? Is there any other starting point you'd suggest?

**Comment by anton-bondarev** [comment]
Yes, I've assigned the issue with you

**Comment by alexkalmuk** [comment]
> May I take that as a reference and give an attempt at the implementation? Is there any other starting point you'd suggest?

@layman-n-ish You can also take a look at our src/drivers/clock, most of them are quite simple.

**Comment by layman-n-ish** [comment]
Hi! SP804 is a **dual-timer** module; I see no other way than initialising two distinct `clock_source` devices for each timer because each timer would have its own `TARGET_HZ`, `IRQ` line, `read()` function etc. Am I right?

**Comment by alexkalmuk** [comment]
> Hi! SP804 is a **dual-timer** module; I see no other way than initialising two distinct `clock_source` devices for each timer because each timer would have its own `TARGET_HZ`, `IRQ` line, `read()` function etc. Am I right?

Hm, I am not sure, but couldn't we use only one of these internal timers?

**Comment by puranjaymohan** [comment]
> Hi! SP804 is a **dual-timer** module; I see no other way than initialising two distinct `clock_source` devices for each timer because each timer would have its own `TARGET_HZ`, `IRQ` line, `read()` function etc. Am I right?

Yes, EPIT is also similar to this timer and has two distinct timers in it with different registers. I think the current situation requires only a single timer as it is being used for frequency generation. I think you should only use a single timer.

Thanks

**Comment by layman-n-ish** [comment]
Yes, that makes sense. Thanks, @puranjaymohan.

**Comment by EugenySvirin** [comment]
I would like to try to finish this issue.
