### ISSUE TITLE
Implement mprotect()

### ISSUE THREAD

**Issue by anton-bondarev** [embox/embox#1815]
mprotect() has not been implemented yet.

**Comment by checker5965** [comment]
Hi @anton-bondarev can you give me some more details about this issue? I would like to take a look at this.

**Comment by anton-bondarev** [comment]
It's a standard POSIX routine ([https://pubs.opengroup.org/onlinepubs/009695399/functions/mprotect.html](https://pubs.opengroup.org/onlinepubs/009695399/functions/mprotect.html ))
It links with mmap.
In Embox there is vmem_set_flags() for set flags to a region, but of cause, it's required to check regions and treat memory subsystem for tasks at all.

**Comment by checker5965** [comment]
Alright. Could you assign it to me?
