### ISSUE TITLE
Implement atexit()

### ISSUE THREAD

**Issue by anton-bondarev** [embox/embox#1816]
atexit() has not been implemented yet

**Comment by sk2sat** [comment]
I would like work on this issue.

**Comment by anton-bondarev** [comment]
@sk2sat I've assigned it with you.

**Comment by sk2sat** [comment]
@anton-bondarev 
thx.
I have a question. Is the application entry point the `main`? Not `_start` or `__libc_start_main`?
If so, I think apps using `atexit()` need to expecitly call `exit()`.

**Comment by anton-bondarev** [comment]
> @anton-bondarev
> thx.
> I have a question. Is the application entry point the `main`? Not `_start` or `__libc_start_main`?
> If so, I think apps using `atexit()` need to expecitly call `exit()`.

@sk2sat 
You should go deeper :).
You have to understand how applications execute in Embox (the similar there is in all systems).  It's not usual loader as Linux where there is start code and system loader which you not available, in Embox you can debug all system parts. I think You should try to set a breakpoint at the start of `ifconfig` command ( for example) and look on backtrace.

@ThePiGrepper open PR #1824, can you try work together? It's rather difficult but interesting system task.

**Comment by anton-bondarev** [comment]
@sk2sat @ThePiGrepper Hi, I've enabled 'atexit' task resource in #1967 Now you can use it and  #1824 for solving the issue

**Comment by ThePiGrepper** [comment]
> @sk2sat @ThePiGrepper Hi, I've enabled 'atexit' task resource in #1967 Now you can use it and #1824 for solving the issue

Nice, Ill take a look at the new code.

**Comment by anton-bondarev** [comment]
Closed by #1824

**Comment by anton-bondarev** [comment]
Closed by #1824
