### ISSUE TITLE
Add unit tests for mkdir

### ISSUE THREAD

**Issue by anton-bondarev** [embox/embox#1820]
You should test creation and destroying virtual directories (VFS_DIR_VIRTUAL)
And also you can use ramdisk with ramfs for testing

**Comment by EugenySvirin** [comment]
May I try this one?

**Comment by anton-bondarev** [comment]
> May I try this one?

Yes, sure! I've assigned it to you!

**Comment by EugenySvirin** [comment]
#2252

**Comment by EugenySvirin** [comment]
#2292

**Comment by EugenySvirin** [comment]
#2340
