### ISSUE TITLE
removing getopt_init()

### ISSUE THREAD

**Issue by ThePiGrepper** [embox/embox#1833]
Apparently getopt_init() is not needed anymore, it would be a good idea to start removing it altogether.

**Comment by ThePiGrepper** [comment]
apparently getopt() tests failed when removing getopt_init(). are you sure getopt_init() isn't needed anymore?

**Comment by alexkalmuk** [comment]
> apparently getopt() tests failed when removing getopt_init(). are you sure getopt_init() isn't needed anymore?

`getopt_init()` is required. It doesn't required for _commnads only_ because it is already called before each command execution - `src/framework/cmd/core.c:33`

**Comment by ThePiGrepper** [comment]
I see. I was wondering about that. thanks for the confirmation. I'll test it and send the patch.

**Comment by alexkalmuk** [comment]
@ThePiGrepper Thank you!

This issue continues here https://github.com/embox/embox/issues/1863
