### ISSUE TITLE
third-party: e2fsprogs not building due to undefined references

### ISSUE THREAD

**Issue by ThePiGrepper** [embox/embox#1843]
There are undefined references to unlikely()/likely() compiler optimization flags.
There's a declaration for those in the third party module itself, however it's been commented out by a patch. Don't know why.
There's also a declaration for those in embox itself, so it would be possible to either:  remove that section of the patch so that it doesnt get commented out, or b) modify the patch so that it references the built-in declaration, instead of that one commented out.

**Comment by alexkalmuk** [comment]
@ThePiGrepper Thank you! I think now the issue can be closed.
