### ISSUE TITLE
Add tests for strpbrk()

### ISSUE THREAD

**Issue by anton-bondarev** [embox/embox#1848]
Implement some test cases for [standard strpbrk()](https://pubs.opengroup.org/onlinepubs/009695399/functions/strpbrk.html)

**Comment by nradk** [comment]
Hi, I would like to work on this. Can you assign the issue to me?

**Comment by anton-bondarev** [comment]
@nradk I've assigned it ot you.
But if you want to take part of GSoC you have to follow the instruction on the wiki ([https://github.com/embox/embox/wiki/Google-Summer-of-Code-2020](https://github.com/embox/embox/wiki/Google-Summer-of-Code-2020) ), send email to any of mentors.

**Comment by nradk** [comment]
@anton-bondarev Thank you. I've sent an email to the mentors a few weeks ago.
