### ISSUE TITLE
Add test for memrchr() & memchr()

### ISSUE THREAD

**Issue by anton-bondarev** [embox/embox#1850]
Implement some test cases for standard routines memrchr() & memchr()

**Comment by nakul-shahdadpuri** [comment]
I would like to work on this issue.

**Comment by anton-bondarev** [comment]
Ok. I've assigned it to you

**Comment by nakul-shahdadpuri** [comment]
#1952 added tests. Awaiting review.
Thank you.

**Comment by anton-bondarev** [comment]
Thanks, done

**Comment by ioannessh** [comment]
Hello, I want to work on this issue.

**Comment by anton-bondarev** [comment]
@ioannessh Hi, I've assinged the issue to you
