### ISSUE TITLE
Add unit tests for strcat() & strncat()

### ISSUE THREAD

**Issue by anton-bondarev** [embox/embox#1852]
Add some test cases for standard routines strcat() & strncat()

**Comment by iosif-t** [comment]
I would like to be assigned to this task but i have a question,should i implement the tests in c using assertions?

**Comment by HumayunMulla** [comment]
I would like to work on this, please assign it to me. Thanks!

**Comment by anton-bondarev** [comment]
@HumayunMulla done

**Comment by andreperezmaselco** [comment]
@anton-bondarev, could you assign this issue to me?

**Comment by anton-bondarev** [comment]
@andreperezmaselco I've assigned it to you.
