### ISSUE TITLE
Add unit tests for strrchr() & strchrnul()

### ISSUE THREAD

**Issue by anton-bondarev** [embox/embox#1854]
There are some test case for strchr(). Implement also unit tests for strchrnul() and strrchr()

**Comment by vladtp** [comment]
Hello, can i get assigned to this?

**Comment by anton-bondarev** [comment]
@vladtp I've assigned it
Have You already sent email to any of mentors?

**Comment by vladtp** [comment]
No, but i will send it ASAP
