### ISSUE TITLE
Add unit tests for strerror()

### ISSUE THREAD

**Issue by anton-bondarev** [embox/embox#1856]
Add some test cases for standard strerror()

**Comment by tanner00** [comment]
Can I be assigned this?

**Comment by anton-bondarev** [comment]
@tanner00 I've assigned
Have you already sent email to any of mentors?

**Comment by tanner00** [comment]
Yes

**Comment by 85ayush** [comment]
Hello I would like to work on this issue, I am new to open source contribution, can you please help me , and I will give my 100%

**Comment by anton-bondarev** [comment]
@85ayush Hi, I've assigned it to you
You should start with [Quick-Start](https://github.com/embox/embox/wiki/Quick-Start). First, build and run Embox on QEMU, and then add tests and prepare a new PR with your changes

**Comment by 85ayush** [comment]
Thank you, I will do my best.

**Comment by 85ayush** [comment]
I have done the steps upto the orange mark on the image below. I mean I
have 1. Clonned
2.installed docker
But where do I have to use the command "docker -machine Is"

**Comment by 85ayush** [comment]
Can you please guide me for the issue described in the before male.

**Comment by 85ayush** [comment]
After using". /scripts/docker/docker_start.sh" Command, at the end it says
can't start container, is it fine or there is some error? and when I use "
make cofload-64/qemu" it says " make: command not found". Can you please
help me with this?

**Comment by 85ayush** [comment]
It says "autoqemu_arch is empty" After using command
"./script/qemu/auto_qemu", can you please help me what does it mean?

**Comment by anton-bondarev** [comment]
@85ayush  Do you use Windows?
I think the simplest way work with Embox on Windows is to install virtual machine (VirtualBox for example) with Linux.
Or you can use WSL2, it works for me

> It says "autoqemu_arch is empty" After using command
> "./script/qemu/auto_qemu"
> 

Have you built Embox?
What template have you used for configuration?

**Comment by 85ayush** [comment]
issue.mkv
<https://drive.google.com/file/d/12UrQxdZDEmochjEL5S_Obs5pAmPbvs5v/view?usp=drive_web>
here I have given the video of what I am doing to resolve the issue, can
you please tell me where I am making mistake. And can you please guide me
how to do it?

**Comment by anton-bondarev** [comment]
@85ayush Hi
First, you have to build a standard Embox template and run it on QEMU

It's enough to do the following commands
```
make confload-x86/qemu
make 
./scripts/qemu/auto_qemu
```
I don't know how I can see where you have done mistakes there are a lot of variants. You must find out in your environment yourself.
Of course, you should ask, when you see trouble when you run the commands. But you have to give more correct descriptions
