### ISSUE TITLE
Add unit tests for memcpy()

### ISSUE THREAD

**Issue by anton-bondarev** [embox/embox#1857]
Add some test cases for standard memcpy()

**Comment by ath-90** [comment]
Hello

Could you please assign this issue to me?

Thanks!

**Comment by anton-bondarev** [comment]
@ath-90 Hello

Do you want to participate Embox GSoC2020? You should send email to one of the mentors as described on wiki page ([https://github.com/embox/embox/wiki/Google-Summer-of-Code-2020](https://github.com/embox/embox/wiki/Google-Summer-of-Code-2020 ))

**Comment by ath-90** [comment]
Thanks. Will do.
