### ISSUE TITLE
Add unit test for memset()

### ISSUE THREAD

**Issue by anton-bondarev** [embox/embox#1859]
Implement some test cases for standard memset()

**Comment by binkoni** [comment]
I would like to get assigned.

**Comment by alexkalmuk** [comment]
@binkoni Ok, assigned this one to you.

**Comment by alexkalmuk** [comment]
Ah, sorry, let's it's your second "good first issue", but we are required to solve only one. Let's finish with https://github.com/embox/embox/pull/1862

**Comment by binkoni** [comment]
Oh I didn't knew about that. thanks

2020년 3월 15일 (일) 오후 7:06, Alex Kalmuk <notifications@github.com>님이 작성:

**Comment by KhaledEmaraDev** [comment]
Hi @alexkalmuk, couls you assign this issue to me? I have already contacted you by email.

**Comment by anton-bondarev** [comment]
@KhaledEmaraDev I've assigned it

**Comment by Jia1018** [comment]
Hello im new here and i would like to start contributing.
Is this thread still open/ not being worked on by anyone ?
If so I would also try to get my fingers wet :)
Just let me know if there are anything i can do.

**Comment by anton-bondarev** [comment]
@Jia1018 I've assigned it to you

**Comment by Jia1018** [comment]
Please excuse me for relying this late. But I noticed that the PR of this issue has already been closed, so i wonder whether you still need me to work on this:)

**Comment by Jia1018** [comment]
Or i can help with another issue:)

**Comment by anton-bondarev** [comment]
@Jia1018 the issue is not closed. You could work on it on another as you wish

**Comment by Jia1018** [comment]
ok, thanks. I'll do my best:)

发自我的iPhone


------------------ Original ------------------

**Comment by semtagg** [comment]
Hi! Is this issue still available? Can I take it?

**Comment by anton-bondarev** [comment]
Hello @semtagg I've assigned it to you
