### ISSUE TITLE
Add support for '%n' format for scanf()

### ISSUE THREAD

**Issue by Deryugin** [embox/embox#1870]
According to POSIX standard https://pubs.opengroup.org/onlinepubs/9699919799/
```
n
    No input is consumed. The application shall ensure that the
corresponding argument is a pointer to the integer into which
shall be written the number of bytes read from the input so far
by this call to the fscanf() functions. Execution of a %n conversion
specification shall not increment the assignment count returned
at the completion of execution of the function. No argument shall
be converted, but one shall be consumed. If the conversion
specification includes an assignment-suppressing character or
a field width, the behavior is undefined.
```

It's required to extend existing `scanf()` implementation with this format and also add corresponding test for `package embox.test.stdio.scanf_test`.

**Comment by RubyOcelot** [comment]
Hi, I would like to take this issue, please assigned to me.

**Comment by Deryugin** [comment]
@RubyOcelot ok!

**Comment by RubyOcelot** [comment]
@Deryugin I've add %n to scanf and test for scanf. but how to run the test and check the correctness? I tried to add it in mod.config but don't work

**Comment by anton-bondarev** [comment]
> I tried to add it in mod.config but don't work

The test fails? Or it is not called?

**Comment by RubyOcelot** [comment]
> > I tried to add it in mod.config but don't work
> 
> The test fails? Or it is not called?

It's not called, the test list doesn't change.
I add a line in mod.config for x86/qemu:
`@Runlevel(1) include embox.test.stdio.scanf_test`

**Comment by anton-bondarev** [comment]
@RubyOcelot Let me see on your module description? (Mybuild file)
