### ISSUE TITLE
usb-net and mass storage do not work together

### ISSUE THREAD

**Issue by alexkalmuk** [embox/embox#1960]
Make sure you have the following modules in `x86/qemu` and network cards removed except `usbnet`:

```
// @Runlevel(2) include embox.driver.net.virtio
@Runlevel(1) include embox.driver.usb.class.mass_storage
@Runlevel(1) include embox.driver.net.usbnet
@Runlevel(2) include embox.driver.usb.hc.ohci_pci
```

Run `./scripts/qemu/auto_qemu_with_usb_storage`. Embox hangs. It looks like to be a problem in usb stack or ohci.

**Comment by anton-bondarev** [comment]
After a 'reset' state has been added during initialization the problem is resolved
```
root@embox:/#lsusb
Bus 000 Device 002 ID 46f4:0001
Bus 000 Device 001 ID 0525:a4a2
Bus 000 Device 000 ID 0000:0000
```
