### ISSUE TITLE
arm/qemu uses 100% one core of host cpu

### ISSUE THREAD

**Issue by anton-bondarev** [embox/embox#1971]
It's enough to use arch_idle() with speeling

**Comment by sk2sat** [comment]
What is "speeling"?
I think this issue can be fix by implementing arch_idle() for arm/qemu(arm926ejs).
Is this recognition correct?

And, does the detailed documentation for Mybuild exist?

**Comment by anton-bondarev** [comment]
> I think this issue can be fix by implementing arch_idle() for arm/qemu(arm926ejs).
> Is this recognition correct?

I mean that 'arm/qemu' uses 'embox.arch.generic.arch' module
```
@Runlevel(0) include embox.arch.arm.arm9.arm926ejs.cpu -> depends embox.arch.generic.arch
```
'embox.arch.generic.arch' has trvial arch_idle implementation
```
void arch_idle(void) {
}
```

Therefore 'idle thread' is never asleep.
As I know there is an assembler instruction which makes CPU sleep until IRQ. you should use one in your arch_idle() implementation

**Comment by anton-bondarev** [comment]
@sk2sat 

> What is "speeling"?
> I think this issue can be fix by implementing arch_idle() for arm/qemu(arm926ejs).
> Is this recognition correct?

Yes, I think You right, I described it above (previous comment).

> And, does the detailed documentation for Mybuild exist?

Unfortunately not, Some information can be found in issue #1774 and you can ask in the issue what exactly you want to know

**Comment by sk2sat** [comment]
Thanks for detailed reply. I'll check it out.
