### ISSUE TITLE
Run Embox on qemu risc-v

### ISSUE THREAD

**Issue by alexkalmuk** [embox/embox#2014]

**Comment by sk2sat** [comment]
I am trying to create riscv/qemu64 template and fix src/arch/riscv/ to work on 64bit,
but is it better to create riscv64/qemu like mips64?

**Comment by anton-bondarev** [comment]
> I am trying to create riscv/qemu64 template and fix src/arch/riscv/ to work on 64bit,
> but is it better to create riscv64/qemu like mips64?

I meant just run existing template riscv/qemu, but of cause, it's better if you create riscv64/qemu to start riscv64 supporting.
I think you should create full riscv64/qemu not only link as mips64

Is MAix BiT riscv64?

**Comment by sk2sat** [comment]
Thanks.
Then I will implement riscv64/qemu(because MAix BiT is riscv64).

**Comment by anton-bondarev** [comment]
Closed by #2053

**Comment by anton-bondarev** [comment]
Closed by #2053
