### ISSUE TITLE
stm32f7-discovery: Network is not working (sometimes) on first reset

### ISSUE THREAD

**Issue by alexkalmuk** [embox/embox#2047]
When you flash stm32f7-discovery (746g or 769i boards, for example) you can wonder why ping is not working. But if you reboot your board (without powering off) - e.g. `monitor reset halt`, then network works fine.

**Comment by anton-bondarev** [comment]
it seems work If interface set up twice 
I added following into start_scrip.inc
```
"ifconfig eth0 down",
"ifconfig eth0 192.168.2.128 netmask 255.255.255.0 hw ether AA:BB:CC:DD:EE:02 up",
```
