### ISSUE TITLE
Create script for loading firmware to MAiX Bit board

### ISSUE THREAD

**Issue by anton-bondarev** [embox/embox#2121]
Create script and wiki page

**Comment by sk2sat** [comment]
I update [wiki page](https://github.com/embox/embox/wiki/MAiX-BiT).
Should the script be placed like scripts/maixbit-flash.sh?

**Comment by anton-bondarev** [comment]
> I update [wiki page](https://github.com/embox/embox/wiki/MAiX-BiT).
> Should the script be placed like scripts/maixbit-flash.sh?

Yes, thanks!
