### ISSUE TITLE
Add GPIO driver for MAiX BiT board

### ISSUE THREAD

**Issue by anton-bondarev** [embox/embox#2145]

**Comment by sk2sat** [comment]
Kendryte K210 has FPIOA. FPIOA configures GPIO role. I think we have to add FPIOA driver before GPIO.

**Comment by anton-bondarev** [comment]
@sk2sat Do you mean "Field Programmable IO Array (FPIOA/IOMUX)"?
Yes, you are right it must be implemented before GPIO, but it can be restricted (only for GPIO), and for testing FPIOA maybe used GPIO. I mean that it seems FPIOA can be implemented as part of this task

**Comment by sk2sat** [comment]
@anton-bondarev Yes, thanks. I'm thinking abount implement drivers/gpio/k210/fpioa,gpio.

**Comment by anton-bondarev** [comment]
Close with #2156
