### ISSUE TITLE
Network manager should be able to monitor connections in run time

### ISSUE THREAD

**Issue by alexkalmuk** [embox/embox#2147]
Currently, netmanager processes the` network` file in `start_script` and after then exits. It would be useful if netmanager can monitor network connections in runtime.

**Comment by vanyaio** [comment]
JFYI: in Linux kernel information about adding/deleting interfaces is obtained with subscribing to kernel notifications using netlink sockets. 
https://olegkutkov.me/2018/02/14/monitoring-linux-networking-state-using-netlink/

**Comment by alexkalmuk** [comment]
Thanks, it looks like a good way.

**Comment by anton-bondarev** [comment]
Closed #2214
