### ISSUE TITLE
armv7-m: Fix SD card to be working with cpu cache enabled

### ISSUE THREAD

**Issue by alexkalmuk** [embox/embox#2163]
There is a comment in `templates/arm/stm32f746g-discovery/mods.conf` (added in https://github.com/embox/embox/pull/2162):

```
    /* Can be enabled after SD card will be fixed. Currently it uses DMA
     * and may become broken. */
    /*
    @Runlevel(0) include embox.arch.arm.armmlib.armv7m_cpu_cache(
        log_level=4,
        sram_nocache_section_size=0x4000,
        nocache_region0_addr=0x60000000, nocache_region0_size=0x00100000
    )
    */
```

We cannot enable cpu cache in this template because DMA is used in SD card controller driver. So we should think about how to fix SD card controller first.

**Comment by anton-bondarev** [comment]
FIxed
