### ISSUE TITLE
inconvenient name server setting

### ISSUE THREAD

**Issue by anton-bondarev** [embox/embox#2179]
It's required change option in mods.conf
```	include embox.net.lib.dns_fixed(nameserver="192.168.0.1")```
 to setup dns (nameserver) in Embox . It's not usefull.
Maybe it's better to enable 'resolv.conf' or add an opportunity to set up it in 'network'

**Comment by alexkalmuk** [comment]
Done in https://github.com/embox/embox/pull/2209, now you can use resolv.conf to declare nameserver.

```
```
