### ISSUE TITLE
Port LVGL to Embox

### ISSUE THREAD

**Issue by anton-bondarev** [embox/embox#2324]
Light and Versatile Graphics Library [https://lvgl.io/](https://lvgl.io/)

**Comment by alexkalmuk** [comment]
@embeddedt We would like to mention that we added basic support for LVGL (btw, awesome library!) to Embox. Here is a [video](https://youtu.be/BrR9AWcMBfE) and [wiki](https://github.com/embox/embox/wiki/LVGL).

**Comment by embeddedt** [comment]
Very cool! :clap:

**Comment by anton-bondarev** [comment]
I think It's done so can be closed.
