### ISSUE TITLE
module dependency cycle errors in first build

### ISSUE THREAD

**Issue by shubhamr2511** [embox/embox#2329]
Hi, I am trying to follow quick start. Its showing some errors in output...not able to make "hello_world" application. Need help.
OS : Ubuntu 20.04
Embox cloned from github repository on Jan 16 2021. (11:02)

shubham@ThinkPad-W520:~/github$ git clone https://github.com/embox/embox
shubham@ThinkPad-W520:~/github$ cd embox/
shubham@ThinkPad-W520:~/github/embox$ sudo apt-get install make gcc build-essential gcc-multilib curl libmpc-dev python
shubham@ThinkPad-W520:~/github/embox$ sudo apt-get install gcc
shubham@ThinkPad-W520:~/github/embox$ sudo apt-get install qemu-system
shubham@ThinkPad-W520:~/github/embox$ make confload-x86/qemu
shubham@ThinkPad-W520:~/github/embox$ make

Output(copied error part only):
...
 MYFILE third-party/bsp/stmf7cube/components/Mybuild
 MYLINK: 890 files 
 CONFIGFILE conf/mods.conf
 CONFIGLINK
 BUILDMODEL
 BUILDGEN /home/shubham/github/embox/build
Error: modules dependency cycle:
	embox.driver.common
	embox.fs.driver.devfs_old
	embox.fs.rootfs
	embox.fs.syslib.file_system_full
Error: modules dependency cycle:
	embox.fs.node
	embox.driver.block_dev
	embox.driver.common
	embox.fs.driver.devfs_old
	embox.fs.rootfs
Error: modules dependency cycle:
	embox.compat.posix.fs.open_old
	embox.compat.posix.fs.dirent_old
	embox.fs.core
	embox.fs.node
	embox.driver.block_dev
	embox.driver.common
	embox.fs.driver.devfs_old
	embox.fs.rootfs
	embox.fs.syslib.file_system_full
Error: modules dependency cycle:
	embox.fs.core
	embox.fs.node
	embox.driver.block_dev
	embox.driver.common
	embox.fs.driver.devfs_old
Error: modules dependency cycle:
	embox.fs.core
	embox.fs.node
	embox.driver.block_dev
	embox.driver.common
	embox.fs.driver.devfs_old
	embox.fs.rootfs
	embox.fs.syslib.file_system_full
Error: modules dependency cycle:
	embox.fs.syslib.fs_full
	embox.fs.core
	embox.fs.node
	embox.driver.block_dev
	embox.driver.common
	embox.fs.driver.devfs_old
	embox.fs.rootfs
	embox.fs.syslib.file_system_full
Error: modules dependency cycle:
	embox.driver.common
	embox.fs.driver.devfs_old
	embox.fs.rootfs
	embox.fs.syslib.file_system_full
Error: modules dependency cycle:
	embox.fs.node
	embox.driver.block_dev
	embox.driver.common
	embox.fs.driver.devfs_old
	embox.fs.rootfs
Error: modules dependency cycle:
	embox.compat.posix.fs.open_old
	embox.compat.posix.fs.dirent_old
	embox.fs.core
	embox.fs.node
	embox.driver.block_dev
	embox.driver.common
	embox.fs.driver.devfs_old
	embox.fs.rootfs
	embox.fs.syslib.file_system_full
Error: modules dependency cycle:
	embox.fs.core
	embox.fs.node
	embox.driver.block_dev
	embox.driver.common
	embox.fs.driver.devfs_old
Error: modules dependency cycle:
	embox.fs.core
	embox.fs.node
	embox.driver.block_dev
	embox.driver.common
	embox.fs.driver.devfs_old
	embox.fs.rootfs
	embox.fs.syslib.file_system_full
Error: modules dependency cycle:
	embox.fs.syslib.fs_full
	embox.fs.core
	embox.fs.node
	embox.driver.block_dev
	embox.driver.common
	embox.fs.driver.devfs_old
	embox.fs.rootfs
	embox.fs.syslib.file_system_full
cp -r -T src/lib/debug/whereami.h /home/shubham/github/embox/build/base/include/debug/whereami.h
cp -r -T src/kernel/task/resource/atexit/atexit.h /home/shubham/github/embox/build/base/include/kernel/task/resource/atexit.h
cp -r -T src/drivers/serial/i8250/8250.h /home/shubham/github/embox/build/base/include/drivers/serial/8250.h
cp -r -T src/drivers/diag/diag.h /home/shubham/github/embox/build/base/include/drivers/diag.h
...

# Making hello_world application : 
shubham@ThinkPad-W520:~/github/embox$ mkdir src/cmds/hello_world
shubham@ThinkPad-W520:~/github/embox$ gedit src/cmds/hello_world/hello_world.c
shubham@ThinkPad-W520:~/github/embox$ gedit src/cmds/hello_world/Mybuild
shubham@ThinkPad-W520:~/github/embox$ gedit conf/mods.conf
shubham@ThinkPad-W520:~/github/embox$ make

## output :
 MYFILE src/cmds/hello_world/Mybuild
 MYLINK: 891 files (1 added)
src/cmds/hello_world/Mybuild:3:36: error: Unrecognized characters '', '', ''.
src/cmds/hello_world/Mybuild:3:62: error: Unrecognized characters '', '', ''.
 CONFIGFILE conf/mods.conf
 CONFIGLINK
conf/mods.conf:194:10: error: Couldn't resolve reference to ModuleType 'embox.cmd.hello_world'.
 BUILDMODEL
 BUILDGEN /home/shubham/github/embox/build
Error: modules dependency cycle:
	embox.driver.common
	embox.fs.driver.devfs_old
	embox.fs.rootfs
	embox.fs.syslib.file_system_full
Error: modules dependency cycle:
	embox.fs.node
	embox.driver.block_dev
	embox.driver.common
	embox.fs.driver.devfs_old
	embox.fs.rootfs
Error: modules dependency cycle:
	embox.compat.posix.fs.open_old
	embox.compat.posix.fs.dirent_old
	embox.fs.core
	embox.fs.node
	embox.driver.block_dev
	embox.driver.common
	embox.fs.driver.devfs_old
	embox.fs.rootfs
	embox.fs.syslib.file_system_full
Error: modules dependency cycle:
	embox.fs.core
	embox.fs.node
	embox.driver.block_dev
	embox.driver.common
	embox.fs.driver.devfs_old
Error: modules dependency cycle:
	embox.fs.core
	embox.fs.node
	embox.driver.block_dev
	embox.driver.common
	embox.fs.driver.devfs_old
	embox.fs.rootfs
	embox.fs.syslib.file_system_full
Error: modules dependency cycle:
	embox.fs.syslib.fs_full
	embox.fs.core
	embox.fs.node
	embox.driver.block_dev
	embox.driver.common
	embox.fs.driver.devfs_old
	embox.fs.rootfs
	embox.fs.syslib.file_system_full
Error: modules dependency cycle:
	embox.driver.common
	embox.fs.driver.devfs_old
	embox.fs.rootfs
	embox.fs.syslib.file_system_full
Error: modules dependency cycle:
	embox.fs.node
	embox.driver.block_dev
	embox.driver.common
	embox.fs.driver.devfs_old
	embox.fs.rootfs
Error: modules dependency cycle:
	embox.compat.posix.fs.open_old
	embox.compat.posix.fs.dirent_old
	embox.fs.core
	embox.fs.node
	embox.driver.block_dev
	embox.driver.common
	embox.fs.driver.devfs_old
	embox.fs.rootfs
	embox.fs.syslib.file_system_full
Error: modules dependency cycle:
	embox.fs.core
	embox.fs.node
	embox.driver.block_dev
	embox.driver.common
	embox.fs.driver.devfs_old
Error: modules dependency cycle:
	embox.fs.core
	embox.fs.node
	embox.driver.block_dev
	embox.driver.common
	embox.fs.driver.devfs_old
	embox.fs.rootfs
	embox.fs.syslib.file_system_full
Error: modules dependency cycle:
	embox.fs.syslib.fs_full
	embox.fs.core
	embox.fs.node
	embox.driver.block_dev
	embox.driver.common
	embox.fs.driver.devfs_old
	embox.fs.rootfs
	embox.fs.syslib.file_system_full
make[4]: '/home/shubham/github/embox/build/base/gen/embox_gcc_env.sh' is up to date.
make[4]: Nothing to be done for 'all'.
make[4]: Nothing to be done for 'all'.
make[4]: Nothing to be done for 'all'.
make[4]: '/home/shubham/github/embox/build/base/gen/embox_gcc_env.sh' is up to date.
make -C third-party/lib/acpica/ MAKEFLAGS=  ROOT_DIR=/home/shubham/github/embox  EMBOX_ROOT_DIR=/home/shubham/github/embox  CONF_DIR=/home/shubham/github/embox/conf  TEMPLATES_DIR=/home/shubham/github/embox/templates  SRC_DIR=/home/shubham/github/embox/src  THIRDPARTY_DIR=/home/shubham/github/embox/third-party  PLATFORM_DIR=/home/shubham/github/embox/platform  PROJECT_DIR=/home/shubham/github/embox/project  SUBPLATFORM_TEMPLATE_DIR=/home/shubham/github/embox/templates  EXTERNAL_BUILD_DIR=/home/shubham/github/embox/build/extbld  LOADABLE_DIR=/home/shubham/github/embox/build/loadable  DOC_DIR=/home/shubham/github/embox/build/doc  BIN ...

## hello_world.c

```
#include <stdio.h>
int main(int argc, char **argv) {
printf("Hello, world!\n");
}
```

## Mybuild
```
package embox.cmd
@AutoCmd
@Cmd(name = "hello_world", help=”First Embox application”)
module hello_world {
source "hello_world.c"
}
```

## mods.conf
```
package genconfig

configuration conf {
	include embox.arch.x86.kernel.arch
	include embox.arch.x86.kernel.locore
	include embox.arch.x86.kernel.context
	include embox.arch.x86.kernel.interrupt

	include embox.arch.x86.vfork
	include embox.arch.x86.stackframe
	include embox.arch.x86.libarch
	include embox.arch.x86.mmu
	include embox.arch.x86.mmuinfo

	@Runlevel(0) include embox.driver.interrupt.i8259
	@Runlevel(0) include embox.driver.clock.pit
	include embox.kernel.time.jiffies(cs_name="pit")
	@Runlevel(2) include embox.driver.clock.tsc
	@Runlevel(2) include embox.driver.clock.hpet

	@Runlevel(2) include embox.driver.serial.i8250(baud_rate=38400)
	@Runlevel(2) include embox.driver.diag(impl="embox__driver__serial__i8250")

	@Runlevel(2) include embox.driver.virtual.null
	@Runlevel(2) include embox.driver.virtual.zero

	@Runlevel(2) include embox.driver.net.loopback
	@Runlevel(2) include embox.driver.net.virtio
	@Runlevel(1) include embox.driver.net.usbnet

	@Runlevel(1) include embox.driver.ide

	@Runlevel(1) include embox.driver.usb.class.mass_storage
	@Runlevel(1) include embox.driver.usb.class.ccid(log_level=4)
	@Runlevel(1) include embox.driver.usb.class.hid
	@Runlevel(2) include embox.driver.usb.hc.ohci_pci

	@Runlevel(2) include embox.lib.debug.whereami
	@Runlevel(2) include embox.profiler.tracing

	@Runlevel(0) include embox.mem.phymem
	@Runlevel(1) include embox.kernel.timer.sys_timer
	@Runlevel(1) include embox.kernel.time.kernel_time

	@Runlevel(2) include embox.kernel.irq
	@Runlevel(2) include embox.kernel.critical
	@Runlevel(2) include embox.kernel.timer.sleep
	@Runlevel(2) include embox.kernel.timer.strategy.head_timer
	@Runlevel(2) include embox.kernel.time.kernel_time
	@Runlevel(2) include embox.kernel.task.multi
	@Runlevel(2) include embox.kernel.thread.core(thread_stack_size=0x20000)
	include embox.kernel.stack(stack_size=0x20000)
	include embox.kernel.sched.strategy.priority_based
	include embox.kernel.thread.signal.sigstate
	include embox.kernel.thread.signal.siginfoq
	include embox.kernel.task.resource.env(env_str_len=64)

	include embox.mem.pool_adapter
	@Runlevel(2) include embox.mem.static_heap(heap_size=0x8000000)
	include embox.mem.heap_bm(heap_size=0x4000000)
	include embox.mem.bitmask

/* for old fs comment dvfs part */
	@Runlevel(2) include embox.fs.node(fnode_quantity=1024)
	@Runlevel(2) include embox.fs.rootfs
	@Runlevel(2) include embox.fs.driver.initfs
	@Runlevel(2) include embox.fs.driver.ramfs
	@Runlevel(2) include embox.fs.driver.ext2
	@Runlevel(2) include embox.fs.driver.fat
	@Runlevel(2) include embox.fs.driver.nfs
	include embox.fs.driver.devfs_old

/* for dvfs comment old fs part */
/*
	@Runlevel(2) include embox.fs.dvfs.core
	@Runlevel(2) include embox.fs.driver.fat_dvfs
	@Runlevel(2) include embox.fs.driver.initfs_dvfs
	@Runlevel(2) include embox.fs.rootfs_dvfs
	include embox.compat.posix.fs.all_dvfs
	include embox.compat.posix.fs.ftruncate_dvfs
	include embox.compat.posix.fs.file_dvfs
	include embox.compat.posix.fs.lseek_dvfs
	include embox.compat.libc.stdio.rename_dvfs
	include embox.fs.driver.devfs_dvfs
*/

	@Runlevel(2) include embox.test.critical
	@Runlevel(2) include embox.test.recursion

	@Runlevel(2) include embox.test.stdio.printf_test
	@Runlevel(2) include embox.test.posix.poll_test
	@Runlevel(2) include embox.test.posix.select_test
	@Runlevel(2) include embox.test.posix.pipe_test
	@Runlevel(2) include embox.test.posix.ppty_test
	@Runlevel(2) include embox.test.stdlib.bsearch_test
	@Runlevel(2) include embox.test.stdlib.qsort_test
	@Runlevel(2) include embox.test.posix.environ_test
	@Runlevel(2) include embox.test.posix.getopt_test

	@Runlevel(1) include embox.test.math.math_test
	@Runlevel(2) include embox.test.math.fpu_context_consistency_test

	@Runlevel(2) include embox.cmd.sh.tish(
				prompt="%u@%h:%w%$", rich_prompt_support=1,
				builtin_commands="exit logout cd export mount umount")
	include embox.init.system_start_service(log_level=3, tty_dev="ttyS0")
	include embox.cmd.service

	include embox.cmd.net.arp
	include embox.cmd.net.netstat
	include embox.cmd.net.arping
	include embox.cmd.net.rarping
	include embox.cmd.net.ifconfig
	include embox.cmd.net.ping
	include embox.cmd.net.iptables
	include embox.cmd.net.route
	include embox.cmd.net.ftp
	include embox.cmd.net.tftp
	include embox.cmd.net.snmpd
	include embox.cmd.net.ntpdate
	include embox.cmd.net.ntpd
	include embox.cmd.net.telnetd
	include embox.cmd.net.nslookup
	include embox.cmd.net.getmail
	include embox.cmd.net.sendmail
	include embox.cmd.net.httpd(use_real_cmd=true, use_parallel_cgi=false)
	include embox.cmd.net.httpd_cgi
	include embox.service.http_admin
	include embox.demo.website
	include embox.cmd.net.netmanager
	include embox.cmd.net.net_service

	include embox.cmd.wc
	include embox.cmd.head

	include embox.cmd.fs.dd
	include embox.cmd.fs.md5sum
	include embox.cmd.fs.uniq
	include embox.cmd.fs.cat
	include embox.cmd.fs.cd
	include embox.cmd.fs.pwd
	include embox.cmd.fs.ls
	include embox.cmd.fs.du
	include embox.cmd.fs.rm
	include embox.cmd.fs.mkfs
	include embox.cmd.fs.mount
	include embox.cmd.fs.more
	include embox.cmd.fs.umount
	include embox.cmd.fs.stat
	include embox.cmd.fs.echo
	include embox.cmd.fs.touch
	include embox.cmd.fs.mkdir
	include embox.cmd.fs.cp
	include embox.cmd.fs.mv

	include embox.cmd.help
	include embox.cmd.man

	include embox.cmd.sys.uname
	include embox.cmd.sys.env
	include embox.cmd.sys.export
	include embox.cmd.sys.version
	include embox.cmd.sys.date
	include embox.cmd.sys.time
	include embox.cmd.sys.shutdown

	include embox.cmd.lsmod
	include embox.cmd.test

	include embox.cmd.proc.nice
	include embox.cmd.proc.renice

	include embox.cmd.proc.thread
	include embox.cmd.proc.top

	include embox.cmd.mmuinfo
	include embox.cmd.hw.mmutrans
	include embox.cmd.mem

	include embox.cmd.ide
	include embox.cmd.lspci
	include embox.cmd.blockdev
	include embox.cmd.hw.lsusb
	include embox.cmd.hw.lsblk
	include embox.cmd.hw.lshw
	include embox.cmd.hw.partition
	include embox.cmd.hw.ccid_cmd

	include embox.cmd.cpuinfo

	include embox.cmd.testing.block_dev_test
	include embox.cmd.testing.ticker
	
	include embox.cmd.hello_world

	@Runlevel(2) include embox.net.core
	@Runlevel(2) include embox.net.skbuff(amount_skb=4000)
	@Runlevel(2) include embox.net.skbuff_data(
				amount_skb_data=4000, data_size=1514,
				data_align=1, data_padto=1,ip_align=false)
	@Runlevel(2) include embox.net.skbuff_extra(
				amount_skb_extra=128,extra_size=10,extra_align=1,extra_padto=1)
	@Runlevel(2) include embox.net.socket
	@Runlevel(2) include embox.net.dev
	@Runlevel(2) include embox.net.af_inet
	@Runlevel(2) include embox.net.ipv4
	@Runlevel(2) include embox.net.arp
	@Runlevel(2) include embox.net.rarp
	@Runlevel(2) include embox.net.icmpv4
	@Runlevel(2) include embox.net.udp
	@Runlevel(2) include embox.net.tcp
	@Runlevel(2) include embox.net.udp_sock
	@Runlevel(2) include embox.net.tcp_sock
	@Runlevel(2) include embox.net.raw_sock
	@Runlevel(2) include embox.net.net_entry
	/* AF_INET, SOCK_STREAM, default */
	include embox.net.lib.dns_file

	include embox.compat.libc.all
	include embox.compat.libc.stdio.asprintf
	include embox.compat.libc.math_builtins
	include embox.compat.posix.pthread_key
	include embox.compat.posix.proc.atexit_stub
	include embox.compat.posix.fs.rewinddir_stub

	include embox.compat.atomic.pseudo_atomic

	include embox.util.LibUtil
	include embox.framework.LibFramework
}

```

**Comment by anton-bondarev** [comment]
@shubhamr2511 It seems that the problem is in your Mybuild
```
src/cmds/hello_world/Mybuild:3:36: error: Unrecognized characters '', '', ''.
src/cmds/hello_world/Mybuild:3:62: error: Unrecognized characters '', '', ''.
```
I seem it can be strange quotes around 'First Embox application'

```
@Cmd(name = "hello_world", help=”First Embox application”)
```

try
```
     @Cmd(name = "hello_world", help="First Embox application")
```

**Comment by shubhamr2511** [comment]
There were many errors when I run `make` command before "hello_world" application. Should I ignore them? . (read #2329 before "Making hello_world application"

**Comment by shubhamr2511** [comment]
@anton-bondarev Thanks its working now!

**Comment by shubhamr2511** [comment]
There are many module dependency errors when I run `make` (without hello_world application). Should I ignore these errors? or how they can be resolved?

**Comment by anton-bondarev** [comment]
> There are many module dependency cycle errors when I run `make` (without hello_world application). Should I ignore these errors? or how they can be resolved?

Yes, unfortunately, You are right. There are several 'dependencies loop' errors. But it is the internal errors. You can ignore it for now. You should only try to not add new cyclic dependencies

**Comment by shubhamr2511** [comment]
@anton-bondarev Thanks!

**Comment by anton-bondarev** [comment]
@shubhamr2511 I've closed the issue.
Fell free open any  issue
