### ISSUE TITLE
Add tests for wcslen()

### ISSUE THREAD

**Issue by anton-bondarev** [embox/embox#2348]

**Comment by VedantParanjape** [comment]
Hi, I would like to work on this issue. I successfully compiled embox and wrote a hello_world example. I am not sure where to add unit test for `wcslen()`, Do I need to add a new source file for testing this function here ?

https://github.com/embox/embox/tree/master/src/tests/c%2B%2B

**Comment by anton-bondarev** [comment]
Closed by #2366

**Comment by 85ayush** [comment]
Hello I would love to work on this issue, I am new to open source contribution( have basic knowledge of git and git hub), and I would give my 100%.

**Comment by wawuwo** [comment]
Hi @anton-bondarev! It appears that this issue could be closed. A couple of comments [higher](#issuecomment-782663943) you mention a PR which resolves this issue.

**Comment by anton-bondarev** [comment]
> Hi @anton-bondarev! It appears that this issue could be closed. A couple of comments [higher](#issuecomment-782663943) you mention a PR which resolves this issue.

Oh, thanks a lot!

**Comment by anton-bondarev** [comment]
> Hello I would love to work on this issue, I am new to open source contribution( have basic knowledge of git and git hub), and I would give my 100%.

@85ayush Sorry for the long reply. You can extend this test for a few more cases or it's better if you work on another issue
