### ISSUE TITLE
date -s 202108311902.40 set wrong time (2021-10-01 19:02:40)

### ISSUE THREAD

**Issue by anton-bondarev** [embox/embox#2492]
Parsing time string is ok ('struct tm date' contains a correct time)
but after
```

	cur_time = mktime(&date);
	tv.tv_sec = cur_time;

	settimeofday(&tv, NULL);
```
the month is 10 instead of 8 and the day 1 instead of 31

**Comment by KlyukinSA** [comment]
@anton-bondarev  i see two rtc devices (find `RTC_DEVICE_DEF`). which of two was used here?

**Comment by anton-bondarev** [comment]
@KlyukinSA I don't think that this issue depends on RTC_DEVICE. You can reproduce it on any qemu template.
As for RTC_DEV. I see RTC only in aarch64/qemu pl031. Dialog RTC is used on only dialog boards.

**Comment by KlyukinSA** [comment]
> Parsing time string is ok ('struct tm date' contains a correct time)

@anton-bondarev  are you sure?


[manpage](https://linux.die.net/man/3/mktime):
> [struct tm::]tm_mon
> The number of months since January, in the range 0 to 11. 

but src/cmds/sys/date.c:set_date
```
end -= 2;
sscanf(end, "%d", &date.tm_mon);
*end = '\0';
```
and not
```
end -= 2;
sscanf(end, "%d", &date.tm_mon);
date.tm_mon -= 1;
*end = '\0';
```

**Comment by anton-bondarev** [comment]
@KlyukinSA Thank you!

> @anton-bondarev are you sure?

No, I'm not sure.
But I checked 'date' cmd on x86/qemu
```
root@embox:/#date -s 202108311902.40

2021-10-01 19:02:39
```

So I think you are right about src/cmds/sys/date.c:set_date

```
end -= 2;
sscanf(end, "%d", &date.tm_mon);
date.tm_mon -= 1;
*end = '\0';
```

could you correct this place and check the result?

**Comment by KlyukinSA** [comment]
@anton-bondarev 
```
root@embox:/#date -s 202108311902.40

2021-08-31 19:02:40
```

**Comment by anton-bondarev** [comment]
@KlyukinSA Thank you very much!
