### ISSUE TITLE
There is a few tests fmod() it is better if some other cases are added

### ISSUE THREAD

**Issue by anton-bondarev** [embox/embox#2797]
There is a few tests fmod() it is better if some other cases are added

**Comment by wawuwo** [comment]
Hi @anton-bondarev! Perhaps, this issue could be closed now? It looks like changes introduced in #2823 resolve it

**Comment by anton-bondarev** [comment]
> Hi @anton-bondarev! Perhaps, this issue could be closed now? It looks like changes introduced in https://github.com/embox/embox/pull/2823 resolve it

@wawuwo Yes, Thanks!
