### ISSUE TITLE
Documentetion architecture portation process

### ISSUE THREAD

**Issue by anton-bondarev** [embox/embox#28]
Describe demands for start project on new platform

**Comment by Deryugin** [comment]
Starting to work on it [on wiki ](https://github.com/embox/embox/wiki/Porting-to-a-new-architecture).

**Comment by anton-bondarev** [comment]
Closed. We've started on wiki and in [Embox documentation repo ](https://github.com/embox/embox-docs). If it becomes actual reopen issue in docs repo
