### ISSUE TITLE
TSC clock source seems to be working incorrectly

### ISSUE THREAD

**Issue by timtim-ww** [embox/embox#2902]
If Embox chooses to use TSC as clock source, it seems to give incorrect data to the module, since kernel system timer loops in a loop of negative(!) 3 to positive 7 nominal seconds, instead of showing somewhat reasonable uptime.
#2899 gives a perspective on that if ran with TSC clock source, otherwise it shows reasonable data
The configuration used is x86/qemu

**Comment by InfernalKn1ght** [comment]
Hello, can I work on this issue?

**Comment by anton-bondarev** [comment]
@InfernalKn1ght sure, I've assigned it with you
