### ISSUE TITLE
Add tests for log10() 

### ISSUE THREAD

**Issue by anton-bondarev** [embox/embox#2960]

**Comment by Khokholeva** [comment]
Hello, I would like to work on this issue

**Comment by anton-bondarev** [comment]
Hello @Khokholeva . I've assigend it with you

**Comment by Khokholeva** [comment]
Currently there are two folders with different test related to math functions - at "src/compat/libc/math/tests" and "src/tests/math". Would it be better to move all tests to the second one for consistency?

**Comment by anton-bondarev** [comment]
> Currently there are two folders with different tests related to math functions - at "src/compat/libc/math/tests" and "src/tests/math". Would it be better to move all tests to the second one for consistency?

@Khokholeva Yes, It would be great! Thanks!

**Comment by Khokholeva** [comment]
Issue can be closed now

**Comment by anton-bondarev** [comment]
Closed by #2968
