### ISSUE TITLE
Add tests for pow() from math.h 

### ISSUE THREAD

**Issue by anton-bondarev** [embox/embox#2962]
Look at https://github.com/embox/embox/blob/master/src/compat/libc/math/tests/sqrt_tests.c

**Comment by twotwozeronine** [comment]
Hello. I want to work on this issue.

**Comment by anton-bondarev** [comment]
Hello @twotwozeronine I've assigened it with you

**Comment by jiuyueshenhua** [comment]
> Hello @twotwozeronine I've assigened it with you

Is The issue done？

**Comment by anton-bondarev** [comment]
@jiuyueshenhua 

> > Hello @twotwozeronine I've assigened it with you
> 
> Is the issue done？
Oh, thanks. I closed it now.
Please could you chose a different Good First Issue?
Or you also can add some other tests for pow() and suggest a PR!

**Comment by anton-bondarev** [comment]
It's done
