### ISSUE TITLE
Add tests for sin() functions

### ISSUE THREAD

**Issue by anton-bondarev** [embox/embox#2963]
Look at https://github.com/embox/embox/blob/master/src/compat/libc/math/tests/sqrt_tests.c

**Comment by AlinaStudyPM** [comment]
Hello, I want to work on this issue

**Comment by anton-bondarev** [comment]
Hello @AlinaStudyPM I've assigned it with you

**Comment by anton-bondarev** [comment]
Look at https://github.com/embox/embox/blob/master/src/compat/libc/math/tests/sqrt_tests.c

**Comment by anton-bondarev** [comment]
Closed by #3050
