### ISSUE TITLE
Add unit-tests for cos() functions (math.h)

### ISSUE THREAD

**Issue by anton-bondarev** [embox/embox#2964]
Look at https://github.com/embox/embox/blob/master/src/compat/libc/math/tests/sqrt_tests.c

**Comment by SurajSonawane2415** [comment]
Hello, I want to work on this issue

**Comment by anton-bondarev** [comment]
@SurajSonawane2415 Hello
I've assigned it with you

**Comment by SurajSonawane2415** [comment]
Thank you, I'm working on it.

**Comment by anton-bondarev** [comment]
Closed #3265
