### ISSUE TITLE
Add tests for asin() from math.h

### ISSUE THREAD

**Issue by anton-bondarev** [embox/embox#2988]
Look at https://github.com/embox/embox/blob/master/src/compat/libc/math/tests/sqrt_tests.c

**Comment by konnnst** [comment]
Hello, can I work on this issue

**Comment by anton-bondarev** [comment]
Hello @konnnst Yes, but if I right you heave been already assigned with #2020 . If you want work on this issue I'll  unassing it from you

**Comment by konnnst** [comment]
> Hello @konnnst Yes, but if I right you heave been already assigned with #2020 . If you want work on this issue I'll unassing it from you

Okay, I'll firstly finish with another
