### ISSUE TITLE
Add support for Bluepill board as well as STM32F103

### ISSUE THREAD

**Issue by rai044der** [embox/embox#3027]
I've already done a part of work, this is based on similar board stm32vl_discovery. Embox boots successfully and even prints out some info, but you can't input anything to console, probably because clocks weren't adjusted for this MCU. 
I've attached patch file with all changes I made.
P.S. extesion of this file is txt, because github didn't accepted it as .patch file for some reason.

[bluepill.txt](https://github.com/embox/embox/files/13167637/bluepill.txt)

**Comment by anton-bondarev** [comment]
Hello @rai044der. Thanks for your efforts. 
I see your PR #3029 it's the bets way to send patches. 
if you want to discuss some questions/ report about  a trouble  or suggest an improvement please feel free to open issue :)
