### ISSUE TITLE
  Clean mruby port and update version

### ISSUE THREAD

**Issue by anton-bondarev** [embox/embox#3064]
Remove 
```
	@InitFS
	source "fib.rb"
```
from Mybuild and place 'fib.rb' into templates which uses it

**Comment by Urtix** [comment]
Hello. I want to work on this issue.

**Comment by anton-bondarev** [comment]
@Urtix hello I've assigned it with you

**Comment by Urtix** [comment]
@anton-bondarev hello, I have made changes to embox/templates/x86/test/lang and embox/third-party/mruby. How to check that everything works as before the changes?

**Comment by anton-bondarev** [comment]
@Urtix Hello



> I have made changes to embox/templates/x86/test/lang and embox/third-party/mruby.

Great. Could you please create a PR

> How to check that everything works as before the changes?

You have to run 'x86/test/lang' at least
