### ISSUE TITLE
stm32f411_blackpill template build fails

### ISSUE THREAD

**Issue by rai044der** [embox/embox#3070]
stm32f411_blackpill build fails with error: 
/home/rai044der/embox_fuzzing/embox/src/drivers/flash/stm32cube_flash/stm32_flash.c:33:10: fatal error: drivers/flash/flash_cache.h: No such file or directory
   33 | #include <drivers/flash/flash_cache.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by anton-bondarev** [comment]
Close by #3071

**Comment by rai044der** [comment]
> @rai044der Thanks/ Have it closed by #3071 ?

everything is working now, thanks
