### ISSUE TITLE
make general gpio interface

### ISSUE THREAD

**Issue by AntonKozlov** [embox/embox#317]
Refactor pins subsystem & gpio subsystem as identical

**Comment by Deryugin** [comment]
What do you mean by pin subsystem?

GPIO system is far from perfect, but I don't think it's necesary to refactor it right now.

**Comment by AntonKozlov** [comment]
There are some remainings of old `pin` subsystems, that was ad-hoc misnamed
gpio.
It's mostly removed, but there are some orphans, like
./src/include/hal/pins.h
./src/include/drivers/pins.h

The gpio have some sharp edges, and this is what the long standing issue is
about.
But you can close this with WONTFIX, if you like.

**Comment by anton-bondarev** [comment]
We redesigned GPIO subsystems (add command to manage it etc).
