### ISSUE TITLE
ld： no .eh_frame_hdr table will be created

### ISSUE THREAD

**Issue by jiuyueshenhua** [embox/embox#3260]
# Description

I followed the wiki's quick start guide.
`make confload-x86/qemu`

`make`

`./scripts/qemu/auto_qemu`

but when I executed `make`, it showed: `/usr/bin/ld: error in ./build/base/obj/embox.o(.eh_frame); no .eh_frame_hdr table will be created`.
![image](https://github.com/embox/embox/assets/109449284/fd76097c-b4ff-478f-9107-6bf2b96b6b2b)

# Environment

1. The command `sudo apt install qemu-system-x86 curl unzip make gcc gcc-10-multilib python3 python-is-python3` executed successfully.
2. Operating System: Windows 10, using WSL2 with Ubuntu 22.
3. GCC version is 12.

![image](https://github.com/embox/embox/assets/109449284/260bede8-23b5-4ece-bf98-4d513e9d84b1)

# Related Information I Found

- [Embox discussion](https://groups.google.com/g/embox-devel/c/GUg99ivxVl8/m/FD-apppRDwAJ)
- [gcc-help](https://gcc.gnu.org/legacy-ml/gcc-help/2009-04/msg00223.html)
- StackOverflow, but the questions were mostly from beginners in simple scenarios.

## Summary

I have a rough idea of what this error means. The solution seems to involve changing the GCC version and modifying the compilation options, but I don't know how to adjust them.

**Comment by anton-bondarev** [comment]
@jiuyueshenhua Hi

message 

> ld： no .eh_frame_hdr table will be created

Is not a problem. the problems are undefined references __divdi3 (and others)
You have to set gcc-multilib for you compiler version. You have installed gcc-10-multilib but your compiler version is 12 as I see
