### ISSUE TITLE
Add unit-tests for cosh() functions (math.h)

### ISSUE THREAD

**Issue by anton-bondarev** [embox/embox#3270]
Look at https://github.com/embox/embox/blob/master/src/compat/libc/math/tests/sqrt_tests.c

**Comment by perminder-17** [comment]
I want to work on this issue.

**Comment by anton-bondarev** [comment]
Ok, I've assigned it with you

**Comment by perminder-17** [comment]
I think we can close this one now? @anton-bondarev

**Comment by anton-bondarev** [comment]
Yes, sure.
Thanks
