### ISSUE TITLE
fatal error: string: No such file or directory

### ISSUE THREAD

**Issue by Chupaw1990** [embox/embox#3287]
Hello! I'm having trouble compiling a project for board(STM32F769I-DISCO).

Configuration: "project/pjsip/stm32f769i-discovery-sip-nuklear".

Error: 
In file included from ../include/pjsua2/persistent.hpp:26,
                 from ../include/pjsua2/account.hpp:27,
                 from ../src/pjsua2/account.cpp:19:
../include/pjsua2/types.hpp:33:10: fatal error: string: No such file or directory
   33 | #include <string>
      |          ^~~~~~~~
compilation terminated.

Version compiler: arm-none-eabi-gcc (15:10.3-2021.07-4) 10.3.1 20210621 (release)
OS: Ubuntu 22.04

**Comment by sycamoremoon** [comment]
Hello, you can see my commit about this issue

**Comment by Chupaw1990** [comment]
Hello!
Yes, indeed, the error with the flags has disappeared.
But the compiler still doesn't find <string>.
It seems the C compiler is used instead of C++ during the build.
Errors:
In file included from ../include/pjsua2/persistent.hpp:26,
                 from ../include/pjsua2/account.hpp:27,
                 from ../src/pjsua2/account.cpp:19:
../include/pjsua2/types.hpp:33:10: fatal error: string: No such file or directory
   33 | #include <string>
      |          ^~~~~~~~
compilation terminated.
In file included from ../include/pjsua2/persistent.hpp:26,
                 from ../include/pjsua2/endpoint.hpp:26,
                 from ../src/pjsua2/endpoint.cpp:19:
../include/pjsua2/types.hpp:33:10: fatal error: string: No such file or directory
   33 | #include <string>
      |          ^~~~~~~~
compilation terminated.
In file included from ../include/pjsua2/persistent.hpp:26,
                 from ../include/pjsua2/json.hpp:26,
                 from ../src/pjsua2/json.cpp:19:
../include/pjsua2/types.hpp:33:10: fatal error: string: No such file or directory
   33 | #include <string>
      |          ^~~~~~~~
compilation terminated.
In file included from ../include/pjsua2/persistent.hpp:26,
                 from ../src/pjsua2/persistent.cpp:19:
../include/pjsua2/types.hpp:33:10: fatal error: string: No such file or directory
   33 | #include <string>
      |          ^~~~~~~~
compilation terminated.
In file included from ../src/pjsua2/types.cpp:19:
../include/pjsua2/types.hpp:33:10: fatal error: string: No such file or directory
   33 | #include <string>
      |          ^~~~~~~~
compilation terminated.
In file included from ../src/pjsua2/siptypes.cpp:19:
../include/pjsua2/types.hpp:33:10: fatal error: string: No such file or directory
   33 | #include <string>
      |          ^~~~~~~~
compilation terminated.
In file included from ../include/pjsua2/persistent.hpp:26,
                 from ../include/pjsua2/account.hpp:27,
                 from ../src/pjsua2/call.cpp:19:
../include/pjsua2/types.hpp:33:10: fatal error: string: No such file or directory
   33 | #include <string>
      |          ^~~~~~~~
compilation terminated.
In file included from ../include/pjsua2/persistent.hpp:26,
                 from ../include/pjsua2/presence.hpp:26,
                 from ../src/pjsua2/presence.cpp:19:
../include/pjsua2/types.hpp:33:10: fatal error: string: No such file or directory
   33 | #include <string>
      |          ^~~~~~~~
compilation terminated.
In file included from ../include/pjsua2/media.hpp:28,
                 from ../src/pjsua2/media.cpp:20:
../include/pjsua2/types.hpp:33:10: fatal error: string: No such file or directory
   33 | #include <string>
      |          ^~~~~~~~

**Comment by sycamoremoon** [comment]
Hey, Embox called thirdpart [PJSIP](https://github.com/pjsip/pjproject) build system, but only use part of it.  In other word, The C++ part is not neccessery but It's no need to remove them. So you saw the error output but still compiled right.

regards

**Comment by Chupaw1990** [comment]
Thanks
