### ISSUE TITLE
include/asm/hal considered harmful

### ISSUE THREAD

**Issue by abusalimov** [embox/embox#331]
##### What steps will reproduce the problem?
1. Go through `src/arch/${ARCH}/include/asm/hal`
2. Look into few header there
3. You will probably see something like:
   
   ```
   #ifndef HAL_XXX_H_
   # error "Do not include this file directly!"
   #endif /* HAL_XXX_H_ */
   ```

It is better to place and name such implementation headers near the corresponding sources and include them using __module_headers(...)
Cc: @anton-bondarev, @AntonKozlov

**Comment by anton-bondarev** [comment]
Won't fix it now
