### ISSUE TITLE
Add tests for cbrt() from math.h 

### ISSUE THREAD

**Issue by anton-bondarev** [embox/embox#3445]
Look at [https://github.com/embox/embox/blob/master/src/compat/libc/math/tests/sqrt_tests.c](https://github.com/embox/embox/blob/master/src/compat/libc/math/tests/sqrt_tests.c)

**Comment by Herculoxz** [comment]
hi

**Comment by anton-bondarev** [comment]
Hi @Herculoxz
I've assigned this issue with you

**Comment by anton-bondarev** [comment]
Closed #3445
