### ISSUE TITLE
Add tests for copysign() from math.h

### ISSUE THREAD

**Issue by anton-bondarev** [embox/embox#3446]
Look at[https://github.com/embox/embox/blob/master/src/compat/libc/math/tests/sqrt_tests.c]( https://github.com/embox/embox/blob/master/src/compat/libc/math/tests/sqrt_tests.c)

**Comment by diamant3** [comment]
Hello, Can i take this issue, thanks!

**Comment by anton-bondarev** [comment]
@diamant3 hi,
Yes, sure.
I've assigned it with you

**Comment by anton-bondarev** [comment]
Closed by #3456
