### ISSUE TITLE
 Add tests for atanh() from math.h

### ISSUE THREAD

**Issue by anton-bondarev** [embox/embox#3452]
Look at [https://github.com/embox/embox/blob/master/src/compat/libc/math/tests/sqrt_tests.c](https://github.com/embox/embox/blob/master/src/compat/libc/math/tests/sqrt_tests.c)

**Comment by LinkolnR** [comment]
Hello @anton-bondarev, I'd like to work on it if possible! please assign me this and allow me to contribute to it

**Comment by anton-bondarev** [comment]
Hello @LinkolnR
Yes, you can work on it. I've assigned it with you
