### ISSUE TITLE
Cleanup the code to return explicit error values

### ISSUE THREAD

**Issue by fsulima** [embox/embox#519]
##### What new or enhanced feature are you proposing?

It is necessary to improve error reporting in existent code base. In many places when the cause of error is unknown the implementation chooses to return -1 value. It coincides with value -EPERM, and higher level routine interpreting error code often misinterprets it or ends up printing "Not permitted" (result of calling strerror(EPERM)). Therefore typically the message gives improper diagnostics, confuses the user and distracts it from the real reason of the failure. Other manifestation is that there are places which do 'return -1' implying 'return -EPERM', therefore code lacks clarity.
##### What goals would this enhancement help you to achieve?

Improve error diagnostics.
Improve code clarity.
##### How are you going to implement the enhancement?

EPERM definition in errno.h is temporarily changed, therefore "Unknown error code. PLEASE REPORT!" will be printed instead. Developers and uses are encouraged to report these cases.
As it is generally impossible to automatically distinguish between correct and erroneous use of 'return -1', only manual cleanup can completely solve the problem.
Cc: @abusalimov

**Comment by Deryugin** [comment]
I suggest to close this issue as too wide.

I don't see how this issue can be solved without rewriting error handling in (almost) the whole project. I guess we can add some details to our codestyle to avoid such issues in future.
