### ISSUE TITLE
Thread thread safety for public API

### ISSUE THREAD

**Issue by fsulima** [embox/embox#543]
##### What new or enhanced feature are you proposing?

Current design for compiled-in application allows to configure for multitasking, in such configuration multiple application would simultaneously use public APIs (e.g. malloc) without explicit inter-application synchronization. In these configurations these APIs are required to be thread safe.
##### What goals would this enhancement help you to achieve?

Allow to execute multiple applications using public APIs in parallel.
##### How are you going to implement the enhancement?

Naive implementation could use global locking mechanism.

**Comment by anton-bondarev** [comment]
Embox has pthread_mutex_ and etc
