### ISSUE TITLE
UNIX processes and POSIX-compatible user-mode APIs

### ISSUE THREAD

**Issue by fsulima** [embox/embox#544]
##### What new or enhanced feature are you proposing?

All studied windowing systems implementations - Nano-X, X11, Wayland - rely on unix processes infrastructure, i.e. server and client applications are implemented as separate interacting processes. Whereas it is possible to transfer some functionality to kernel mode, it doesn't appear to be a good solution from various viewpoints.
##### What goals would this enhancement help you to achieve?

There are numerous benefits of having of having implemented UNIX processes, one of which is scalability required to efficiently run windowing systems.

**Comment by anton-bondarev** [comment]
There are some implemented and used some processes API (vfork() for example) in Embox
