### ISSUE TITLE
slab misuses memory

### ISSUE THREAD

**Issue by AntonKozlov** [embox/embox#596]
##### What steps will reproduce the problem?
1. slab_init:385 allocates memory from __heap and not uses it
2. Moreover, it's treated as a start of a memory region to be managed, but first allocated page could be not start; or some allocations could occur in past
3. cache_grow:144 allocates from __phymem! And puts that to ptr_to_page, that think it from __heap.
##### What is the expected output? What do you see instead?

Rainbow and ponies are expected =(
Cc: @alexkalmuk

**Comment by anton-bondarev** [comment]
If it is actual, reopen
