### ISSUE TITLE
Forbid include <module/...> in headers

### ISSUE THREAD

**Issue by AntonKozlov** [embox/embox#607]
##### What steps will reproduce the problem?
1. Consider src/include/net/tcp.h:23 @ 42efe6e
   
   ```
   #include <module/embox/net/tcp_sock.h>
   ```
2. netfilter is including <net/tcp.h> and has compile error, when tcp_sock is not in build.
##### What is the expected output? What do you see instead?

Netfilter become dependent on tcp_sock, while it's almost impossible to maintain such dependence
Cc: @anton-bondarev, @abusalimov, @HaK1R

**Comment by Deryugin** [comment]
I use this <module/...> includes in headers to have access to options from other modules. I wonder if this is possible without it.

**Comment by AntonKozlov** [comment]
It creates very implicit dependencies. when unsatisfied, they results in ugly 'missing header' build error from compiler and only compiler, build system don't know anything about them.
If we are going to extended build system to catch such dependencies, it's ok to have module header include in global headers. But it seems not going that way, so best option is to avoid them. I'm not insist on technical method (like lint) to fail a build, if some headers found.

Regarding you argument, without good example, it's look like encapsulation violation. That's required, but in rather rare cases.
I think that the rest of such inclusions was necessary because of a design problems. Options supposed to be local for module, so you're sure it's affects only small part of behaviour. Otherwise, it's not different from global config.h, where all option values are stored.

**Comment by Deryugin** [comment]
What do you mean by global config header? I can't find any header which duplicates module options.
For example, let's grep build folder from the master branch with x86/dvfs template:
```bash
$ grep thread_stack_size -rn ./build/
./build/base/gen/include/config/embox/kernel/thread/core.h:7:#ifndef OPTION_NUMBER_embox__kernel__thread__core__thread_stack_size
./build/base/gen/include/config/embox/kernel/thread/core.h:8:#define OPTION_NUMBER_embox__kernel__thread__core__thread_stack_size 8192
```
As you see, this constant is defined just in one header.

Consider following example: POSIX/LibC functions often deal with file names and paths, and buffers for them are being used. It makes sense to get buffer size from options of the VFS.  Now it's done in the following way: src/fs/dvfs.h has <config/embox/fs/dvfs.h> included, and after that if you include <fs/dvfs.h>, you can access those parameters.

That's not very handy, but how else this could be done?

**Comment by AntonKozlov** [comment]
Sorry for confuse you, config.h is hypotetical file (actually, there was such in previous versions of BS). Some effort was spent to split options to modules.

Your example is good enough, as long as config/dvfs.h included to dvfs.h only. But it should not be included to any other headers except dvfs's.

I'd like to suggets disscussion on follow:

Next step in the example to include fs/dvfs.h in some stdio.h. Then, everyone who include stdio.h will get implicit dependecy on dvfs, which is not natural.

For the moment I can't suggest better solution than current. Maybe stdio (existed LibCStdio?) module with exported header stdio.h and dependency on dvfs could help

**Comment by anton-bondarev** [comment]
@AntonKozlov Won't fix?
