### ISSUE TITLE
harddisk_pio seems to misfunction with nsects greater than one

### ISSUE THREAD

**Issue by AntonKozlov** [embox/embox#623]
##### What steps will reproduce the problem?
1. e2e9d8e, x86/nonvga_debug, include embox.fs.driver.ntfs, run on qemu with hda as ntfs-formatted image
2. ntfs tries to read 19456 position of size 2 blocks
##### What is the expected output? What do you see instead?

irq on that write not asserted, and status register holding 0x58, which could be considered as precached read. However, if irq waiting skipped on DRDY and DRQ on, half of sector read right, another one consists from zero, which is spotted by ntfs.

Reading by one sector everytime seems to be ok (made in 7d3133b)
Cc: @fsulima, @sikmir

**Comment by anton-bondarev** [comment]
now closed, reopen If it is reproduced
