### ISSUE TITLE
mmap review

### ISSUE THREAD

**Issue by AntonKozlov** [embox/embox#628]
##### What steps will reproduce the problem?
mmap_nommu (src/mem/mmap/mmap_nommu.c) seems to have untidy implementation, requiring fixes (f47069f, #620). Requesting review.
Cc: @abusalimov, @sikmir

**Comment by Deryugin** [comment]
It seems that this issue is outdated as file was changed a number of times since 2013. I will remove dead code from that file and close this issue.
