### ISSUE TITLE
mkfs -t [etfs,ffs] does not format correctly

### ISSUE THREAD

**Issue by alexkalmuk** [embox/embox#679]
##### What steps will reproduce the problem?
1. On host:

  ```
dd if=/dev/zero of=disk.img bs=1M count=8
mkfs.vfat -F 12 disk.img
  ```
  and then create file f.txt on disk.img
2. `make confload-x86/nonvga_debug` and `run auto_qemu -hda disk.img`
```
root@embox:/#mkdir /mnt
root@embox:/#mkfs -t etfs /dev/hda
root@embox:/#mount -t etfs dev/hda /mnt
root@embox:/#ls /mnt
```

##### What is the expected output? What do you see instead?
The same is for ffs
Cc: @anton-bondarev, @mrgaz, @HaK1R

**Comment by anton-bondarev** [comment]
Removed drivers etfs & ffs
