### ISSUE TITLE
ioctl defining macros should contain argument size

### ISSUE THREAD

**Issue by AntonKozlov** [embox/embox#702]
##### What steps will reproduce the problem?

For example, TIOCGETA is `_IOR('t', 1, struct termios)`, but called like `ioctl(fd, TIOCSETA, termios)` -- termios is of `const struct termios *termios` (src/compat/posix/termios.c)
##### What is the expected output? What do you see instead?

TIOCGETA should be defined as `_IOR('t', 1, struct termios *)` (actually `_IOR('t', 1, const struct termios *)`)

Isn't it?
Cc: @anton-bondarev, @abusalimov

**Comment by anton-bondarev** [comment]
@AntonKozlov 
I don't agree
```
int tcgetattr(int fd, struct termios *termios) {
	return ioctl(fd, TIOCGETA, termios);
}
```
termios a pointer to struct termios (buffer)
TIOCGETA is a request in this case which contains 'buffer ' size
`#define	TIOCGETA	_IOR('t', 1, struct termios)`
`#define _IOR(type, nr, arg)   _IOC(_IOC_READ, type, nr, sizeof(arg))`
so ioctl called with sizeof (struct termios) in second arg and  buffer for struct termios in third arg

**Comment by anton-bondarev** [comment]
@AntonKozlov May be close this?

**Comment by AntonKozlov** [comment]
Agree, I was under misconception that ioctl system is capable to pass values via parameters. After looking closer, pointers are everywhere and everything looks consistent
