### ISSUE TITLE
extend termios_ops

### ISSUE THREAD

**Issue by AntonKozlov** [embox/embox#719]
##### What new or enhanced feature are you proposing?

extend termios_ops with operations performed by tty driver
##### What goals would this enhancement help you to achieve?

Strict separation of tty code: character processing and associated actions (sleep, output, ...)
##### How are you going to implement the enhancement?

Move some of processing to termios_ops

**Comment by anton-bondarev** [comment]
@AntonKozlov Can you please give more details?

**Comment by AntonKozlov** [comment]
It was fixed as #1055
