### ISSUE TITLE
Some drivers still do not use REG_STORE/REG_LOAD

### ISSUE THREAD

**Issue by AntonKozlov** [embox/embox#720]
##### What steps will reproduce the problem?
1. ns16550, xuartlite not uses REG_LOAD/REG_STORE
2. It should, as in general memory-mapped registers access is more compilcated than (volatile void *) access

**Comment by Deryugin** [comment]
`REG_LOAD`/`REG_STORE` and structure are both fine, so I'm closing this issue.
