### ISSUE TITLE
execve should initialize environment of new process

### ISSUE THREAD

**Issue by AntonKozlov** [embox/embox#724]
Current implementation does not use envp at all.

**Comment by El-Mohamed** [comment]
Hi, I would try to work on this.

**Comment by alexkalmuk** [comment]
@Abnaby hi, I assigned you to this issue.

**Comment by Abnaby** [comment]
The main parameter `*envp` is not specified by POSIX.
If you take a look at the process memory map you will see that `envp[]` is just above `argv[]`.

**Comment by alexkalmuk** [comment]
>  The main parameter *envp is not specified by POSIX

Are you sure https://pubs.opengroup.org/onlinepubs/000095399/functions/exec.html?

**Comment by alexkalmuk** [comment]
It is not the main parameter, but environment variables.
