### ISSUE TITLE
64-bit clean?

### ISSUE THREAD

**Issue by andreiw** [embox/embox#822]
Is embox 64-bit clean yet? I noticed there are only 32-bit variants for things like x86 and ppc, hence the question...

A

**Comment by anton-bondarev** [comment]
You are right, unfortunately embox don't support any 64 bits architecture!

**Comment by AntonKozlov** [comment]
For those who interested, seems like 64bit port start should not be really hard
http://kazlauskas.me/entries/x64-uefi-os-1.html

**Comment by Deryugin** [comment]
Now we have partial Aarch64 and e2k support (they both are 64-bit platforms). Not all modules are 64-bit clean, but that's enough for minimal build (MMU/interrupts/console commands/etc).
