### ISSUE TITLE
Embox + docker on mac os X

### ISSUE THREAD

**Issue by AnastasiaSulyagina** [embox/embox#947]
Не могу запустить ембокс в докере. С командой 

```
sudo qemu-system-i386 -kernel ./build/base/bin/embox -m 256 -net nic,vlan=0,model=virtio,macaddr=AA:BB:CC:DD:EE:02 -net tap,script=./scripts/qemu/start_script,downscript=./scripts/qemu/stop_script,vlan=0 -nographic
```

все нормально, а с 

```
dr ./scripts/qemu/auto_qemu -s -S
```

висит с 

```
ioctl(TUNSETIFF): Device or resource busy
Enable IP Forwarding for eth0
net.ipv4.ip_forward = 1
```

**Comment by AnastasiaSulyagina** [comment]
И как раньше билдила через crosstool теперь не могу для дебага запустить

**Comment by AntonKozlov** [comment]
Можно и без докера

-s -S останавливает qemu до подсоединения дебагера. Пока дебагером не подцепиться, дальше загрузка не пойдет.

Насколько понимаю, поведение одинаковое с докерм и без?

**Comment by AnastasiaSulyagina** [comment]
Дебаггер подцеплен, но он не слышит без докера. А как дебаггер к докеру подключить не совсем понятно.

**Comment by AntonKozlov** [comment]
Последовательность отладки
1. запустить qemu -s -S
2. подцепиться дебагером (remote в eclipse, `target extended-remote :1234` в gdb)
3. Сказать continue в дебагере или eclipse

Не совсем понял, что значит "не слышит без докера"

Для отладки в докере вместо `gdb` на хост машине надо запускать gdbhostwrapper (https://github.com/embox/embox/wiki/Emdocker#gdb). Для эклипса есть готовая конфигурация для дебага scripts/docker/qemu_on_docker.launch, она должна появиться в меню дебаг конфигураций.

Если всё равно не сработает, дайте пожалуйста последовательность, что Вы делали и что видели по пути.

**Comment by AnastasiaSulyagina** [comment]
Я сейчас пока поставила виртуалку убунты, там доделаю, а потом когда время будет, попробую повторить. 
Не слышит - не подключается и выдает timeout.

**Comment by anton-bondarev** [comment]
@AntonKozlov Won't fix?
